### ISSUE TITLE
前端依赖安装失败

### ISSUE THREAD

**Issue by gsfish** [DasSecurity-Labs/AoiAWD#7]
在 Frontend 中执行 `npm install` 时报错，debug 日志如下：

```
24606 verbose notsup SKIPPING OPTIONAL DEPENDENCY: Valid OS:    darwin
24606 verbose notsup SKIPPING OPTIONAL DEPENDENCY: Valid Arch:  any
24606 verbose notsup SKIPPING OPTIONAL DEPENDENCY: Actual OS:   linux
24606 verbose notsup SKIPPING OPTIONAL DEPENDENCY: Actual Arch: x64
24607 verbose stack Error: node-sass@4.11.0 postinstall: `node scripts/build.js`
24607 verbose stack Exit status 1
24607 verbose stack     at EventEmitter.<anonymous> (/usr/lib/node_modules/npm/node_modules/npm-lifecycle/index.js:332:16)
24607 verbose stack     at EventEmitter.emit (events.js:314:20)
24607 verbose stack     at ChildProcess.<anonymous> (/usr/lib/node_modules/npm/node_modules/npm-lifecycle/lib/spawn.js:55:14)
24607 verbose stack     at ChildProcess.emit (events.js:314:20)
24607 verbose stack     at maybeClose (internal/child_process.js:1047:16)
24607 verbose stack     at Process.ChildProcess._handle.onexit (internal/child_process.js:287:5)
24608 verbose pkgid node-sass@4.11.0
24609 verbose cwd /home/gsfish/Tools/Defense/AoiAWD/Frontend
24610 verbose Linux 5.4.63-1-lts
24611 verbose argv "/usr/bin/node" "/usr/bin/npm" "install"
24612 verbose node v14.10.0
24613 verbose npm  v6.14.7
24614 error code ELIFECYCLE
24615 error errno 1
24616 error node-sass@4.11.0 postinstall: `node scripts/build.js`
24616 error Exit status 1
24617 error Failed at the node-sass@4.11.0 postinstall script.
24617 error This is probably not a problem with npm. There is likely additional logging output above.
24618 verbose exit [ 1, true ]
```

修改 `package.json` 中 `node-sass` 的版本可解决上述问题：

```
"node-sass": "^4.12.0"
```

**Comment by aodzip** [comment]
大佬确定可以解决问题的话欢迎提交PR

**Comment by gsfish** [comment]
> 大佬确定可以解决问题的话欢迎提交PR

已经提交啦
